pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - '#approved-reviews-by>=1'
      - author=@OneKeyHQ/all
      - '-draft'
    actions:
      merge:
        method: merge
