name: Package & Publish

on: workflow_dispatch

jobs:
  npm-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Run lint & tests
        run: |
          yarn install --forzen-lockfile
          yarn test
          yarn unittest
      - name: Build & publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          yarn build
          yarn publish --access public
